---
    - name: Install dependencies
      package:
        name: "{{ item }}"
        state: present
      loop:
        - wget
        - tar
    
    - name: Download Prometheus tarball
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-{{ prometheus_arch }}.tar.gz"
        dest: /tmp/prometheus.tar.gz
        mode: 0755
      vars:
        prometheus_version: "2.30.3"
        prometheus_arch: "amd64"
    
    - name: Transfer Prometheus tarball to target machines
      copy:
        src: /tmp/prometheus.tar.gz
        dest: /tmp/prometheus.tar.gz
        mode: 0755
      delegate_to: localhost
    
    - name: Extract Prometheus
      command: "tar -xvf /tmp/prometheus.tar.gz -C /tmp/"
    
    - name: Move Prometheus files
      command: "mv /tmp/prometheus-{{ prometheus_version }}.linux-{{ prometheus_arch }}/ /etc/prometheus"
    
    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /etc/prometheus/data
        - /etc/prometheus/rules
        - /etc/prometheus/wal
    
    - name: Copy Prometheus configuration
      copy:
        src: /etc/prometheus/prometheus.yml
        dest: /etc/prometheus/prometheus.yml
    
    - name: Set ownership and permissions
      file:
        path: "{{ item }}"
        owner: prometheus
        group: prometheus
        recurse: yes
      loop:
        - /etc/prometheus/
        - /etc/prometheus/data/
        - /etc/prometheus/rules/
        - /etc/prometheus/wal/
    
    - name: Create systemd service
      template:
        src: prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service
    
    - name: Reload systemd
      systemd:
        name: prometheus
        enabled: yes
        state: restarted

